/**
 * Common French merchants. A match anywhere in the document is more reliable than guessing from the header.
 * Names that are also everyday words (Total, Orange, Free, Match…) are left out: the header detection covers them.
 */
export const KNOWN_MERCHANTS = [
  'Carrefour Market',
  'Carrefour City',
  'Carrefour Express',
  'Carrefour',
  'E.Leclerc',
  'Leclerc',
  'Intermarché',
  'Auchan',
  'Lidl',
  'Aldi',
  'Super U',
  'Hyper U',
  'Système U',
  'Monoprix',
  'Franprix',
  'Picard',
  'Grand Frais',
  'Biocoop',
  'Naturalia',
  'Netto',
  'Leader Price',
  'Décathlon',
  'Leroy Merlin',
  'Castorama',
  'Brico Dépôt',
  'Ikea',
  'Fnac',
  'Darty',
  'Boulanger',
  'Gifi',
  'Kiabi',
  'Zara',
  'H&M',
  'Primark',
  'Sephora',
  'Nocibé',
  "McDonald's",
  'Burger King',
  'KFC',
  'Starbucks',
  'Subway',
  'Domino’s',
  'Uber Eats',
  'Deliveroo',
  'Uber',
  'SNCF',
  'RATP',
  'TotalEnergies',
  'Shell',
  'Esso',
  'Amazon',
  'Cdiscount',
  'EDF',
  'Engie',
  'SFR',
  'Bouygues Telecom',
  'Netflix',
  'Spotify',
  'Deezer',
  'Disney+',
  'Canal+',
] as const
