/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AppBudgetsBudgetIdRouteRouteImport } from './routes/_app/budgets/$budgetId/route'
import { Route as AppBudgetsBudgetIdIndexRouteImport } from './routes/_app/budgets/$budgetId/index'
import { Route as AppBudgetsBudgetIdExpensesRouteImport } from './routes/_app/budgets/$budgetId/expenses'
import { Route as AppBudgetsBudgetIdSettingsIndexRouteImport } from './routes/_app/budgets/$budgetId/settings/index'
import { Route as AppBudgetsBudgetIdSettingsBudgetRouteImport } from './routes/_app/budgets/$budgetId/settings/budget'
import { Route as AppBudgetsBudgetIdSettingsCategoriesRouteImport } from './routes/_app/budgets/$budgetId/settings/categories'
import { Route as AppBudgetsBudgetIdSettingsIncomesRouteImport } from './routes/_app/budgets/$budgetId/settings/incomes'
import { Route as AppBudgetsBudgetIdSettingsMembersRouteImport } from './routes/_app/budgets/$budgetId/settings/members'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBudgetsBudgetIdRouteRoute = AppBudgetsBudgetIdRouteRouteImport.update({
  id: '/budgets/$budgetId',
  path: '/budgets/$budgetId',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsBudgetIdIndexRoute = AppBudgetsBudgetIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBudgetsBudgetIdRouteRoute,
} as any)
const AppBudgetsBudgetIdExpensesRoute =
  AppBudgetsBudgetIdExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AppBudgetsBudgetIdRouteRoute,
  } as any)
const AppBudgetsBudgetIdSettingsIndexRoute =
  AppBudgetsBudgetIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppBudgetsBudgetIdRouteRoute,
  } as any)
const AppBudgetsBudgetIdSettingsBudgetRoute =
  AppBudgetsBudgetIdSettingsBudgetRouteImport.update({
    id: '/settings/budget',
    path: '/settings/budget',
    getParentRoute: () => AppBudgetsBudgetIdRouteRoute,
  } as any)
const AppBudgetsBudgetIdSettingsCategoriesRoute =
  AppBudgetsBudgetIdSettingsCategoriesRouteImport.update({
    id: '/settings/categories',
    path: '/settings/categories',
    getParentRoute: () => AppBudgetsBudgetIdRouteRoute,
  } as any)
const AppBudgetsBudgetIdSettingsIncomesRoute =
  AppBudgetsBudgetIdSettingsIncomesRouteImport.update({
    id: '/settings/incomes',
    path: '/settings/incomes',
    getParentRoute: () => AppBudgetsBudgetIdRouteRoute,
  } as any)
const AppBudgetsBudgetIdSettingsMembersRoute =
  AppBudgetsBudgetIdSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => AppBudgetsBudgetIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof AppOnboardingRoute
  '/profile': typeof AppProfileRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/health': typeof ApiHealthRoute
  '/invite/$token': typeof InviteTokenRoute
  '/budgets/$budgetId': typeof AppBudgetsBudgetIdRouteRouteWithChildren
  '/budgets/$budgetId/expenses': typeof AppBudgetsBudgetIdExpensesRoute
  '/budgets/$budgetId/': typeof AppBudgetsBudgetIdIndexRoute
  '/budgets/$budgetId/settings/budget': typeof AppBudgetsBudgetIdSettingsBudgetRoute
  '/budgets/$budgetId/settings/categories': typeof AppBudgetsBudgetIdSettingsCategoriesRoute
  '/budgets/$budgetId/settings/incomes': typeof AppBudgetsBudgetIdSettingsIncomesRoute
  '/budgets/$budgetId/settings/members': typeof AppBudgetsBudgetIdSettingsMembersRoute
  '/budgets/$budgetId/settings/': typeof AppBudgetsBudgetIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof AppOnboardingRoute
  '/profile': typeof AppProfileRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/health': typeof ApiHealthRoute
  '/invite/$token': typeof InviteTokenRoute
  '/budgets/$budgetId/expenses': typeof AppBudgetsBudgetIdExpensesRoute
  '/budgets/$budgetId': typeof AppBudgetsBudgetIdIndexRoute
  '/budgets/$budgetId/settings/budget': typeof AppBudgetsBudgetIdSettingsBudgetRoute
  '/budgets/$budgetId/settings/categories': typeof AppBudgetsBudgetIdSettingsCategoriesRoute
  '/budgets/$budgetId/settings/incomes': typeof AppBudgetsBudgetIdSettingsIncomesRoute
  '/budgets/$budgetId/settings/members': typeof AppBudgetsBudgetIdSettingsMembersRoute
  '/budgets/$budgetId/settings': typeof AppBudgetsBudgetIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/profile': typeof AppProfileRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/api/health': typeof ApiHealthRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/budgets/$budgetId': typeof AppBudgetsBudgetIdRouteRouteWithChildren
  '/_app/budgets/$budgetId/expenses': typeof AppBudgetsBudgetIdExpensesRoute
  '/_app/budgets/$budgetId/': typeof AppBudgetsBudgetIdIndexRoute
  '/_app/budgets/$budgetId/settings/budget': typeof AppBudgetsBudgetIdSettingsBudgetRoute
  '/_app/budgets/$budgetId/settings/categories': typeof AppBudgetsBudgetIdSettingsCategoriesRoute
  '/_app/budgets/$budgetId/settings/incomes': typeof AppBudgetsBudgetIdSettingsIncomesRoute
  '/_app/budgets/$budgetId/settings/members': typeof AppBudgetsBudgetIdSettingsMembersRoute
  '/_app/budgets/$budgetId/settings/': typeof AppBudgetsBudgetIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/profile'
    | '/login'
    | '/signup'
    | '/api/health'
    | '/invite/$token'
    | '/budgets/$budgetId'
    | '/budgets/$budgetId/expenses'
    | '/budgets/$budgetId/'
    | '/budgets/$budgetId/settings/budget'
    | '/budgets/$budgetId/settings/categories'
    | '/budgets/$budgetId/settings/incomes'
    | '/budgets/$budgetId/settings/members'
    | '/budgets/$budgetId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/profile'
    | '/login'
    | '/signup'
    | '/api/health'
    | '/invite/$token'
    | '/budgets/$budgetId/expenses'
    | '/budgets/$budgetId'
    | '/budgets/$budgetId/settings/budget'
    | '/budgets/$budgetId/settings/categories'
    | '/budgets/$budgetId/settings/incomes'
    | '/budgets/$budgetId/settings/members'
    | '/budgets/$budgetId/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/onboarding'
    | '/_app/profile'
    | '/_auth/login'
    | '/_auth/signup'
    | '/api/health'
    | '/invite/$token'
    | '/_app/budgets/$budgetId'
    | '/_app/budgets/$budgetId/expenses'
    | '/_app/budgets/$budgetId/'
    | '/_app/budgets/$budgetId/settings/budget'
    | '/_app/budgets/$budgetId/settings/categories'
    | '/_app/budgets/$budgetId/settings/incomes'
    | '/_app/budgets/$budgetId/settings/members'
    | '/_app/budgets/$budgetId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/budgets/$budgetId': {
      id: '/_app/budgets/$budgetId'
      path: '/budgets/$budgetId'
      fullPath: '/budgets/$budgetId'
      preLoaderRoute: typeof AppBudgetsBudgetIdRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets/$budgetId/': {
      id: '/_app/budgets/$budgetId/'
      path: '/'
      fullPath: '/budgets/$budgetId/'
      preLoaderRoute: typeof AppBudgetsBudgetIdIndexRouteImport
      parentRoute: typeof AppBudgetsBudgetIdRouteRoute
    }
    '/_app/budgets/$budgetId/expenses': {
      id: '/_app/budgets/$budgetId/expenses'
      path: '/expenses'
      fullPath: '/budgets/$budgetId/expenses'
      preLoaderRoute: typeof AppBudgetsBudgetIdExpensesRouteImport
      parentRoute: typeof AppBudgetsBudgetIdRouteRoute
    }
    '/_app/budgets/$budgetId/settings/': {
      id: '/_app/budgets/$budgetId/settings/'
      path: '/settings'
      fullPath: '/budgets/$budgetId/settings/'
      preLoaderRoute: typeof AppBudgetsBudgetIdSettingsIndexRouteImport
      parentRoute: typeof AppBudgetsBudgetIdRouteRoute
    }
    '/_app/budgets/$budgetId/settings/budget': {
      id: '/_app/budgets/$budgetId/settings/budget'
      path: '/settings/budget'
      fullPath: '/budgets/$budgetId/settings/budget'
      preLoaderRoute: typeof AppBudgetsBudgetIdSettingsBudgetRouteImport
      parentRoute: typeof AppBudgetsBudgetIdRouteRoute
    }
    '/_app/budgets/$budgetId/settings/categories': {
      id: '/_app/budgets/$budgetId/settings/categories'
      path: '/settings/categories'
      fullPath: '/budgets/$budgetId/settings/categories'
      preLoaderRoute: typeof AppBudgetsBudgetIdSettingsCategoriesRouteImport
      parentRoute: typeof AppBudgetsBudgetIdRouteRoute
    }
    '/_app/budgets/$budgetId/settings/incomes': {
      id: '/_app/budgets/$budgetId/settings/incomes'
      path: '/settings/incomes'
      fullPath: '/budgets/$budgetId/settings/incomes'
      preLoaderRoute: typeof AppBudgetsBudgetIdSettingsIncomesRouteImport
      parentRoute: typeof AppBudgetsBudgetIdRouteRoute
    }
    '/_app/budgets/$budgetId/settings/members': {
      id: '/_app/budgets/$budgetId/settings/members'
      path: '/settings/members'
      fullPath: '/budgets/$budgetId/settings/members'
      preLoaderRoute: typeof AppBudgetsBudgetIdSettingsMembersRouteImport
      parentRoute: typeof AppBudgetsBudgetIdRouteRoute
    }
  }
}

interface AppBudgetsBudgetIdRouteRouteChildren {
  AppBudgetsBudgetIdExpensesRoute: typeof AppBudgetsBudgetIdExpensesRoute
  AppBudgetsBudgetIdIndexRoute: typeof AppBudgetsBudgetIdIndexRoute
  AppBudgetsBudgetIdSettingsBudgetRoute: typeof AppBudgetsBudgetIdSettingsBudgetRoute
  AppBudgetsBudgetIdSettingsCategoriesRoute: typeof AppBudgetsBudgetIdSettingsCategoriesRoute
  AppBudgetsBudgetIdSettingsIncomesRoute: typeof AppBudgetsBudgetIdSettingsIncomesRoute
  AppBudgetsBudgetIdSettingsMembersRoute: typeof AppBudgetsBudgetIdSettingsMembersRoute
  AppBudgetsBudgetIdSettingsIndexRoute: typeof AppBudgetsBudgetIdSettingsIndexRoute
}

const AppBudgetsBudgetIdRouteRouteChildren: AppBudgetsBudgetIdRouteRouteChildren =
  {
    AppBudgetsBudgetIdExpensesRoute: AppBudgetsBudgetIdExpensesRoute,
    AppBudgetsBudgetIdIndexRoute: AppBudgetsBudgetIdIndexRoute,
    AppBudgetsBudgetIdSettingsBudgetRoute:
      AppBudgetsBudgetIdSettingsBudgetRoute,
    AppBudgetsBudgetIdSettingsCategoriesRoute:
      AppBudgetsBudgetIdSettingsCategoriesRoute,
    AppBudgetsBudgetIdSettingsIncomesRoute:
      AppBudgetsBudgetIdSettingsIncomesRoute,
    AppBudgetsBudgetIdSettingsMembersRoute:
      AppBudgetsBudgetIdSettingsMembersRoute,
    AppBudgetsBudgetIdSettingsIndexRoute: AppBudgetsBudgetIdSettingsIndexRoute,
  }

const AppBudgetsBudgetIdRouteRouteWithChildren =
  AppBudgetsBudgetIdRouteRoute._addFileChildren(
    AppBudgetsBudgetIdRouteRouteChildren,
  )

interface AppRouteChildren {
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppBudgetsBudgetIdRouteRoute: typeof AppBudgetsBudgetIdRouteRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfileRoute: AppProfileRoute,
  AppBudgetsBudgetIdRouteRoute: AppBudgetsBudgetIdRouteRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
